from .populate_data import Command as PopulatePostsCommand
from .populate_categories import Command as PopulateCategoriesCommand
from .populate_space_agency import Command as populatespaceagencyCommand